---
# tasks file for ec2_launch
#


- name: ec2_launch_config
  ec2:
    key_name: ssh_key
    instance_type: t2.micro
    instance_profile_name: AdminS3access
    image: ami-02e60be79e78fef21
    volumes:
      - device_name: /dev/sda1
        delete_on_termination: yes
        volume_type: gp2
        volume_size: 8
    wait: yes
    group_id: sg-0bd6469705bbe6ed2
    count: 1
    instance_tags:
      Name: ansible_deployed_node
    vpc_subnet_id: subnet-b5f383dd
    assign_public_ip: yes
    region: ap-south-1
  register: ec2

- name: Add the IP to group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: ec2_hosts
  with_items: "{{ ec2.instances }}"

- name: SSH Connection to Active
  delegate_to: "{{ item.public_dns_name }}"
  wait_for_connection:
    delay: 60
  with_items: "{{ ec2.instances }}"


